MONTHLY_BUDGET_CSV_PATTERN: str = "monthly_budget[0-9]*.csv"
EXPENSES_STATEMENT_CSV_PATTERN: str = "SpendAccount[a-zA-Z0-9-]*[0-9]*-[0-9]*.csv"
MONTHLY_BUDGET_DIR: str = "./"
EXPENSES_STATEMENT_PRE_CATEGORISE_DIR: str = "./pre-categorise/"
EXPENSES_STATEMENT_POST_CATEGORISE_DIR: str = "./post-categorise/"
